# Site settings
title: MacMladen
email: macmladen@bluefish.rs
description: "Musings about code. And life."
baseurl: ""
url: "http://macmladen.com"

# Social contacts
twitter_username:    MacMladen
github_username:     MacMladen
facebook_username:   MaclMaden
linkedin_username:   macmladen
googleplus_username: MacMladen
drupalorg_username:  MacMladen
medium_username:     MacMladen
stackoverflow_username: 1099667/MacMladen
apple:               bluefish.rs

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Exclude files
exclude: ["less", "Gruntfile.js", "ISSUES", "package.json", "node_modules", ".idea", "CNAME", "ISSUES"]
